---
title: Indivisible Hawaii
timezone: Pacific/Honolulu
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  resources:
    title: Resources
    output: true
    permalink: "/resource/:path"
  successes:
    title: Successes
    output: true
    permalink: "/success/:path"
  teams:
    title: Teams
    output: true
    permalink: "/team/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    pinned: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    embed-code: 
    news-link: 
    layout: post
    island: 
    chapter: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: resources
  values:
    is featured: false
    main-image: 
    layout: resource
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
- scope:
    path: ''
    type: teams
  values:
    layout: team
    teamtag: 
    team-email: 
    team-description: 
subtitle: Democracy with Aloha
email: info@indivisiblehawaii.org
address: 
baseurl: 
url: https://indivisiblehawaii.org
logo: "/uploads/2019%20IH%20Sq%20sticker%20v9%20Ok.jpg"
twitter_username: "@IndivisibleHI"
twitter-embed: <a class="twitter-timeline" data-height="400" href="https://twitter.com/IndivisibleHI?ref_src=twsrc%5Etfw">Tweets
  by IndivisibleHI</a> <script async src="https://platform.twitter.com/widgets.js"
  charset="utf-8"></script>
facebook_username: Indivisible-Hawaii-102454510271701
facebook_feed: <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FIndivisible-Hawaii-102454510271701&tabs=timeline&width=300&height=400&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=364621774216107"
  width="300" height="400" style="border:none;overflow:hidden" scrolling="no" frameborder="0"
  allowTransparency="true" allow="encrypted-media"></iframe>
background-image: "/uploads/website%20pix%2011.jpg"
member-count: 2000+
footer-title: Let's take action together.
default-image: "/uploads/ib-logo-vert.png"
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: 
permalink: "/:categories/:title"
emptyArray: []
